import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import AppProvider, { useApp } from "./context/app-context";
import { Toaster } from "./components/ui/toaster";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Homely",
  description: "Generated by create next app",
  icons: {
    icon: "../app/assets/logo-full.png",
  },
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <AppProvider>
        <body className={inter.className}>{children}</body>
        <Toaster />
      </AppProvider>
    </html>
  );
}
